name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  DB_USERNAME: 'postgres'
  DB_PASSWORD: 'postgres'
  DB_HOST: '127.0.0.1'
  DB_DATABASE: 'testing'
  DB_PORT: '5432'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.3 ]
        postgres-version: [ 15, 16 ]

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_USER: ${{ env.DB_USERNAME }}
          POSTGRES_DB: ${{ env.DB_DATABASE }}
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: pdo_pgsql

      - name: Composer install
        run: composer install

      - name: Lint
        run: composer lint

      - name: Static Analysis
        run: composer stan

      - name: Rector
        run: composer rector

      - name: Test
        run: composer test
